# ItemBan Plugin Configuration
# Uses only MiniMessage format
# See: https://docs.advntr.dev/minimessage/format.html

# Combat System Configuration
combat:
  enabled: true
  duration: 15
  kill-on-logout: true
  show-actionbar: true
  actionbar-update-interval: 10
  banned-items:
    - "ENDER_PEARL"
    - "CHORUS_FRUIT"
    - "GOLDEN_APPLE"
    - "ENCHANTED_GOLDEN_APPLE"
    - "TOTEM_OF_UNDYING"
    - "DIAMOND_SWORD"
    - "NETHERITE_SWORD"
    - "ELYTRA"
  region-lock:
    enabled: false
    regions:
      - "spawn"
      - "arena"
      - "pvp"

# Ender Pearl Cooldown System
ender-pearl:
  enabled: true
  cooldown: 5
  show-cooldown-message: true
  global-cooldown: true

# World-specific bans
world-bans:
  enabled: true
  worlds:
    spawn:
      - "ENDER_CRYSTAL"
      - "TNT"
      - "RESPAWN_ANCHOR"
      - "WITHER_SKELETON_SKULL"
      - "DIAMOND_SWORD"
      - "ELYTRA"
    pvp:
      - "TOTEM_OF_UNDYING"
      - "GOLDEN_APPLE"
    creative:
      - "BARRIER"
      - "COMMAND_BLOCK"
      - "STRUCTURE_BLOCK"

# Message Configuration
messages:
  enabled: true
  actionbar-enabled: true

  # Prefix with custom hex color
  prefix: "<color:#ff00b1><bold>ITEMBAN</bold></color> <gray>»</gray>"

  # All messages in MiniMessage format
  item-banned-region: "<red><bold>Dieses Item ist in dieser Region nicht erlaubt!"
  item-banned-combat: "<red><bold>Dieses Item ist während des Kampfes nicht erlaubt!"
  item-banned-world: "<red><bold>Dieses Item ist in dieser Welt nicht erlaubt!"
  wand-received: "<green>Regions-Wand erhalten! Linksklick und Rechtsklick zum Markieren."
  region-created: "<green>Region '<white>{name}</white>' erfolgreich erstellt!"
  region-deleted: "<green>Region '<white>{name}</white>' wurde gelöscht!"
  pos1-set: "<green>Position 1 gesetzt: <white>{x}, {y}, {z}</white>"
  pos2-set: "<green>Position 2 gesetzt: <white>{x}, {y}, {z}</white>"
  no-permission: "<red>Du hast keine Berechtigung für diesen Befehl!"
  config-reloaded: "<green>Konfiguration erfolgreich neu geladen!"
  in-combat: "<red>Du bist jetzt im Kampf für {duration} Sekunden!"
  combat-end: "<green>Du bist nicht mehr im Kampf!"
  combat-actionbar: "<color:#fc0000><underlined>COMBAT:</underlined> <white>{time}s</white>"
  combat-logout-death: "<red>{player} ist während des Kampfes offline gegangen und gestorben!"
  combat-region-leave-denied: "<red>Du kannst diese Region nicht während des Kampfes verlassen!"
  ender-pearl-cooldown: "<red><bold>Ender Pearl ist noch für <yellow>{time}</yellow> Sekunden im Cooldown!"

# Wand Configuration
wand:
  material: "DIAMOND_AXE"
  name: "<gold><bold>Regions-Wand</bold></gold>"
  lore:
    - "<gray>Linksklick: Position 1 setzen</gray>"
    - "<gray>Rechtsklick: Position 2 setzen</gray>"
    - "<gray>Verwende <white>/itemban create <n></white> um eine Region zu erstellen</gray>"