name: ItemBan-BladeSMP
version: '${project.version}'
main: bladesmp.itembanfolia.ItemBanPlugin
description: ${project.description}
api-version: '1.21'
folia-supported: true
authors: MrEnte_
website: https://github.com/MrK4mo/ItemBan-Folia

permissions:
  itemban.admin:
    description: Administrative permissions for ItemBan
    default: op
  itemban.bypass:
    description: Bypass item restrictions
    default: false
  itemban.command:
    description: Use ItemBan commands
    default: op

# Commands are registered programmatically in Paper plugins
# No YAML-based command declarations allowed